web/config/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static



admin.site.site_title = 'アプリ'
admin.site.site_header = 'アプリ管理画面'
admin.site.index_title = 'システム管理'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('', include('teams.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/teams/urls.py
from django.urls import path
from . import views



app_name = 'teams'

urlpatterns = [
    # サポートページ
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    # アカウントリスト
    path('accounts/list/', views.accounts_list, name='accounts_list'),
    # チーム
    path('team/create/', views.team_create, name='team_create'),
    path('team/list/', views.team_list, name='team_list'),
    path('team/<str:teamname>/update/', views.team_update, name='team_update'),
    path('team/<str:teamname>/delete/', views.team_delete, name='team_delete'),
    path('team/<str:teamname>/', views.team_detail, name='team_detail'),
    path('team/<str:teamname>/member/', views.team_detail_member, name='team_detail_member'),
    path('team/<str:teamname>/feature/', views.team_detail_feature, name='team_detail_feature'),
    path('team/<str:teamname>/desired_condition/', views.team_detail_desired_condition, name='team_detail_desired_condition'),
    # メンバー
    path('team/<str:teamname>/member/add/', views.team_member_add, name='team_member_add'),
    path('team/<str:teamname>/member/list/', views.team_member_list, name='team_member_list'),
    path('team/<str:teamname>/member/delete/<str:username>/', views.team_member_delete, name='team_member_delete'),
    # プロフィール
    path('<str:username>/', views.account_detail, name='account_detail'),
    path('<str:username>/feature/', views.account_detail_feature, name='account_detail_feature'),
    path('<str:username>/desired_condition/', views.account_detail_desired_condition, name='account_detail_desired_condition'),
    path('<str:username>/update/', views.account_profile_update, name='account_profile_update'),
    # 通知
    path('<str:username>/notification/', views.notification, name='notification'),
    path('<str:username>/notification/application/<uuid:id>/', views.application_detail, name='application_detail'),
    path('<str:username>/notification/invitation/<uuid:id>/', views.invitation_detail, name='invitation_detail'),
    path('<str:username>/notification/member_approval/<uuid:id>/', views.member_approval_detail, name='member_approval_detail'),
    path('<str:username>/notification/official/<uuid:id>/', views.official_detail, name='official_detail'),
    # リクエスト送信
    path('team/<str:teamname>/application/create/', views.application_create, name='application_create'),
    path('<str:username>/application/reply/create/<uuid:id>/', views.application_reply_create, name='application_reply_create'),
    # 招待送信
    path('<str:username>/invitation/create/', views.invitation_create, name='invitation_create'),
]

web/teams/models/faq.py
from django.db import models



class Question(models.Model):
    """
    よくある質問のモデル。
    アドミンページからの追加しかできない。
    """
    class Meta():
        db_table = 't_question'
        verbose_name = 'よくある質問'
        verbose_name_plural = 'よくある質問'

    id = models.AutoField(primary_key=True, editable=False)
    question = models.CharField(max_length=255, null=False, blank=False)
    awnser = models.CharField(max_length=1000, null=False, blank=False)

    def __str__(self):
        return self.question

web/teams/views/access.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import redirect
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured, PermissionDenied
from django.contrib.auth.mixins import AccessMixin



class OnlyYouMixin(UserPassesTestMixin):
    """
    本人のみアクセスできる Mixin。

    Attributes
    ----------
    raise_exception : bool
        raise exception を許すかの bool。
    """
    raise_exception = True

    def test_func(self):
        """
        request.user の username がアクセスしようとしている username と同じか確認する

        Returns
        -------
        bool
            True ならアクセス可能
            False ならアクセス不可
        """
        user = self.request.user
        return user.username == self.kwargs['username']



class OnlyOwnerMixin(UserPassesTestMixin):
    """
    チームのオーナーのみアクセスできる Mixin。

    Attributes
    ----------
    raise_exception : bool
        raise exception を許すかの bool。
    """
    raise_exception = True

    def test_func(self):
        """
        request.user の teamname がアクセスしようとしている teamname と同じか、 request.user はオーナーか確認する

        Returns
        -------
        bool
            True ならアクセス可能、False ならアクセス不可
        """
        user = self.request.user
        if user.is_authenticated:
            return user.user_profile.is_owner == True and user.user_profile.team.teamname == self.kwargs.get('teamname')
        else:
            return False



class CustomAccessMixin(AccessMixin):
    """
    AnonymousUser のみのアクセスに対応した Mixin を作成するため AccessMixin をカスタムしたクラス。
    親クラスと違うのは get_home_url の名前、 handle_no_permission の処理。
    """
    home_url = None

    def get_home_url(self):
        """
        AnonymousUser なら、 self.home_url もしくは 孫クラスの home_url にリダイレクトする関数。

        Raises
        ------
        ImproperlyConfigured
            ログインユーザーがアクセスした時にリダイレクトさせる URL がないため。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            孫クラスで定義した home_url もしくは、 settings.LOGIN_REDIRECT_URL に redirect。
        """
        home_url = self.home_url or settings.LOGIN_REDIRECT_URL
        if not home_url:
            raise ImproperlyConfigured(
                '{0} is missing the home_url attribute. Define {0}.home_url, settings.LOGIN_REDIRECT_URL, or override '
                '{0}.get_home_url().'.format(self.__class__.__name__)
            )
        return redirect(home_url)

    def handle_no_permission(self):
        """
        permission がないユーザーの画面処理。

        Parameters
        ----------
        self.raise_exception : bool
            孫クラスで定義。 raise_exception を許すかどうか。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            同クラスの get_home_url 関数の返り値の redirect。

        Raises
        ------
        PermissionDenied
            raise_exception True か request.user が未ログインのため。
            普通なら anonymous_user がこの処理を通ることはない（小クラスの dispatch 関数で anonymous_user がこの関数の処理を通らないようにしているため）。
        """
        if self.raise_exception or self.request.user.is_anonymous:
            raise PermissionDenied(self.get_permission_denied_message())
        return self.get_home_url()



class AnonymousRequiredMixin(CustomAccessMixin):
    """
    AnonymousUser のみアクセスできる Mixin。

    Examples
    --------
    AnonymousRequiredMixin を継承するのみで使用可能。
    home_url は任意。

    class SampleView(AnonymousRequiredMixin, TemplateView):
        home_url = 'views.home'
        # more ...
    """

    def dispatch(self, request, *args, **kwargs):
        """
        request.user はアクセス権限があるか判断する。
        ログインユーザーはアクセスできない。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            親クラスの get_home_url 関数の返り値の redirect。

        Any
            view の親クラスの dispatch 関数。
        """
        if request.user.is_authenticated:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

web/teams/views/application.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from .access import OnlyYouMixin
from teams.models import Team, Notification
from teams.forms import ApplicationCreateForm, ApplicationUpdateForm
from .team import TeamDetailBaseView



class ApplicationCreateView(LoginRequiredMixin, CreateView, TeamDetailBaseView):
    """
    チームリクエストを作成する。
    """
    template_name = 'teams/application_create.html'
    form_class = ApplicationCreateForm
    success_url = 'teams:team_detail'
    team_model = Team

    def form_valid_for_create_view(self, form):
        return super().form_valid(form)

    def form_valid(self, form):
        """
        application object に必要な情報を登録する。
        同じチームに所属している場合、無効になる。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            success_url に redirect。
        """
        self.object = form.save(commit=False)
        self.object.team = self.team_model.objects.get(teamname=self.kwargs.get('teamname'))
        self.user_team = self.request.user.user_profile.team
        if self.object.team == self.user_team or self.object.team.disclosed is False:
            return redirect(self.success_url, teamname=self.kwargs.get('teamname'))

        self.object.mode = 'application'
        self.object.from_user = self.request.user

        member = self.object.team.belonging_user_profiles.all()
        owner_profile = member.filter(is_owner=True)[0]
        self.object.to_user = owner_profile.user
        self.object.save()
        return self.form_valid_for_create_view(form)

    def get_success_url(self):
        """
        super().form_valid(form) が実行された後にリダイレクトする URL を取得する関数。

        See Also
        --------
        self.object.team.teamname : str
            form_valid 関数で取得したリクエストを送ろうとしている Team の teamname。
        """
        return reverse(self.success_url, kwargs={'teamname': self.object.team.teamname})

application_create = ApplicationCreateView.as_view()



class ApplicationReplyCreateView(LoginRequiredMixin, OnlyYouMixin, UpdateView):
    """
    リクエストの承認とその返答に必要なURLを入力するための view。
    """
    template_name = 'teams/notification/application_reply_create.html'
    form_class = ApplicationUpdateForm
    success_url = 'teams:notification'

    def form_valid_for_create_view(self, form):
        return super().form_valid(form)

    def form_valid(self, form):
        """
        チームリクエストオブジェクトを True にするのとURLをオブジェクトに登録する関数。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            get_success_url 関数で指定した url に redirect。
        """
        self.object = Notification.objects.get(id=self.kwargs.get('id'))
        if self.object.from_user == self.request.user or self.object.is_proceeded is False:
            return redirect('teams:home')
        self.object.is_proceeded = True
        self.object.invitation_url = form.cleaned_data['invitation_url']
        self.object.save()
        return self.form_valid_for_create_view(form)

    def get_context_data(self, **kwargs):
        """
        チームリクエストオブジェクトの編集に必要なオブジェクトを取得する関数。

        Returns
        -------
        dict
            チームリクエストオブジェクト入り ctx。
        """
        ctx = super().get_context_data(**kwargs)
        ctx['object'] = Notification.objects.get(id=self.kwargs.get('id'))
        return ctx

    def get_object(self):
        """
        URL に必要なパラメータを取得する関数。
        """
        return get_object_or_404(get_user_model(), username=self.kwargs.get('username'))

    def get_success_url(self):
        """
        super().form_valid(form) が実行された後にリダイレクトする URL を取得する関数。

        See Also
        --------
        self.request.user.username : str
            request.user の username。
        """
        return reverse(self.success_url, kwargs={'username': self.request.user.username})

application_reply_create = ApplicationReplyCreateView.as_view()

web/teams/views/invitation.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from teams.models import UserProfile
from teams.forms import InvitationCreateForm
from .profile import UserProfileBaseView



class InvitationCreateView(LoginRequiredMixin, CreateView, UserProfileBaseView):
    """
    ユーザー招待を作成する。
    """
    template_name = 'teams/invitation_create.html'
    form_class = InvitationCreateForm
    success_url = 'teams:account_detail'

    def form_valid(self, form):
        """
        invitation object に必要な情報を登録する。
        オーナーでない、もしくは本人に送信しようとしている場合、無効になる。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            success_url に redirect。
        """
        self.object = form.save(commit=False)
        if self.request.user.user_profile.is_owner == False:
            return redirect(self.success_url, username=self.kwargs.get('username'))
        self.object.mode = 'invitation'
        self.object.from_user = self.request.user
        self.object.invitation_user = get_user_model().objects.get(username=self.kwargs.get('username'))
        self.object.to_user = self.object.invitation_user
        if self.request.user == self.object.to_user or self.object.to_user.disclosed is False:
            return redirect(self.success_url, username=self.kwargs.get('username'))
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        """
        super().form_valid(form) が実行された後にリダイレクトする URL を取得する関数。

        See Also
        --------
        self.object.invitation_user : str
            招待を送ったユーザーの username
        """
        return reverse(self.success_url, kwargs={'username': self.object.invitation_user.username})

invitation_create = InvitationCreateView.as_view()

web/teams/views/profile.py
from django.shortcuts import get_object_or_404, resolve_url, redirect
from django.views.generic import DetailView, UpdateView, ListView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.db.models import Q
from functools import reduce
from operator import and_
from .access import OnlyYouMixin
from teams.models import Notification, UserProfile
from teams.forms import UserProfileUpdateForm



class UserProfileBaseView(DetailView):
    """
    ユーザープロフィールのデータを取得する
    """
    template_name = 'teams/accounts/profile_extends_base.html'
    model = UserProfile
    context_object_name = 'user_profile'

    def get_context_data(self, **kwargs):
        """
        ユーザープロフィール情報を取得する関数。

        Returns
        -------
        dict
            ユーザープロフィールオブジェクト入り ctx。
        """
        context = super().get_context_data(**kwargs)
        user = get_user_model().objects.get(username=self.kwargs.get('username'))
        context['user_profile'] = user.user_profile
        return context

    def get_object(self):
        return get_object_or_404(get_user_model(), username=self.kwargs.get('username'))


class UserProfileDetailGameView(UserProfileBaseView):
    """
    プロフィール下段のゲームを表示する
    """
    template_name = 'teams/accounts/account_detail_game.html'
    model = UserProfile

account_detail = UserProfileDetailGameView.as_view()



class UserProfileDetailFeatureView(UserProfileBaseView):
    """
    プロフィール下段の特徴を表示する
    """
    template_name = 'teams/accounts/account_detail_feature.html'
    model = UserProfile

account_detail_feature = UserProfileDetailFeatureView.as_view()



class UserProfileDetailDesiredConditionView(UserProfileBaseView):
    """
    プロフィール下段の希望条件を表示する
    """
    template_name = 'teams/accounts/account_detail_desired_condition.html'
    model = UserProfile

account_detail_desired_condition = UserProfileDetailDesiredConditionView.as_view()



class UserProfileUpdateView(LoginRequiredMixin, OnlyYouMixin, UpdateView):
    """
    プロフィールを更新する
    """
    template_name = 'teams/accounts/profile_update.html'
    model = UserProfile
    form_class = UserProfileUpdateForm
    success_url = 'teams:account_detail'

    def get_object(self):
        """
        URL に必要なパラメータを取得する関数。
        """
        return get_object_or_404(UserProfile, user=self.request.user)

    def get_success_url(self):
        """
        更新処理が完了した後に遷移する URL を取得する関数。
        """
        return resolve_url(self.success_url, username=self.kwargs.get('username'))

account_profile_update = UserProfileUpdateView.as_view()



class UserListView(ListView):
    """
    ユーザーの一覧表示・検索を行う。
    仕組みは TeamListView と同じ。
    """
    template_name = 'teams/accounts/accounts_list.html'
    model = UserProfile
    paginate_by = 100

    def get_queryset(self):
        """
        検索フォームに keyword が入力されたら、ユーザープロフィールモデルから検索をする処理。

        Returns
        -------
        Queryset
            検索ワードによって作られたクエリ。

        See Also
        --------
        keyword : html 検索バーから受け取った文字列
        """
        queryset = UserProfile.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            exclusion = set([' ', '　'])
            q_list = ''
            for i in keyword:
                if i in exclusion:
                    pass
                else:
                    q_list += i
            query = reduce(and_, [Q(name__icontains=q) |
                                    Q(introduction__icontains=q) |
                                    Q(desired_condition__icontains=q)
                                    for q in q_list])
            queryset = queryset.filter(query)
        return queryset

accounts_list = UserListView.as_view()

web/teams/templates/teams/team_profile/team_detail.html
{% extends 'teams/team_profile/team_extends_base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'teams/scss/team_profile/dist/team_detail.css' %}">
{% endblock %}

{% block profile_content %}

  <div class="container">
    <div class="game-all">
      {% if object.game_title.all %}
        {% for game in object.game_title.all %}
          <p class='game'>{{ game }}</p>
        {% endfor %}
      {% else %}
        <p>ゲームタイトルを現在選択していません。</p>
      {% endif %}
    </div>
  </div>

{% endblock %}

web/teams/templates/teams/team_profile/team_detail_desired_condition.html
{% extends 'teams/team_profile/team_extends_base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'teams/scss/team_profile/dist/team_detail_desired_condition.css' %}">
{% endblock %}


{% block profile_content %}

  <div class="container">
    <div class="desired-condition-all">
      {% if team.disclosed is True %}

      {% if team.desired_job %}
      <p class="desired-job">希望枠</p>
      <div class="job-section">
        {% for job in team.desired_job.all %}
        <p class='job'>{{ job }}</p>
        {% endfor %}
      </div>
      {% else %}
      <p class='desired-job'>希望枠は現在公開されていません</p>
      {% endif %}

      {% if team.desired_condition %}
      <p>{{ team.desired_condition }}</p>
      {% if request.user.user_profile.team is None %}
      <p class='send-invitation'>
        <a href="{% url 'teams:application_create' team.teamname %}" class="btn btn--blue btn--radius">リクエストを送る</a>
      </p>
      {% endif %}
      {% endif %}
      {% else %}
      <p class="send-invitation">条件は現在公開されていません</p>
      {% endif %}
    </div>
  </div>

{% endblock %}

web/teams/templates/teams/team_profile/team_detail_feature.html
{% extends 'teams/team_profile/team_extends_base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'teams/scss/team_profile/dist/team_detail_feature.css' %}">
{% endblock %}

{% block profile_content %}
  <div class="container">
    <div class='feature-all'>
      {% if object.feature.all %}
      {% for feature in object.feature.all %}
      <p class="feature">{{ feature }}</p>
      {% endfor %}
      {% else %}
      <p>特徴は現在選択されていません。</p>
      {% endif %}
    </div>
  </div>

{% endblock %}

web/teams/templates/teams/team_profile/team_detail_member.html
{% extends 'teams/team_profile/team_extends_base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'teams/scss/team_profile/dist/team_detail_member.css' %}">
{% endblock %}

{% block profile_content %}

  <div class='custom-container'>
    <div class='member-profile-all'>
      <div class="member-profile-section">
        <img src="{{ owner_profile_icon_url }}" alt="アイコン" class='member-icon'>
        <p class="member-name">{{ owner_profile_name }}</p>
        <p class="member-username">@{{ owner_profile_user_username }}</p>
        <p class="job">オーナー</p>
        <a href="{% url 'teams:account_detail' owner_profile_user_username %}"></a>
      </div>

      {% if member_profile %}
        {% for member in member_profile %}
          <div class='member-profile-section'>
            <img src="{{ member.icon.url }}" alt="アイコン" class='member-icon'>
            <p class="member-name">{{ member.name | truncatechars:12 }}</p>
            <p class="member-username">@{{ member.user.username }}</p>
            <p class="job">メンバー</p>
            <a href="{% url 'teams:account_detail' member.user.username %}"></a>
          </div>
        {% endfor %}
      {% endif %}
    </div>

    {% if request.user.user_profile.team == team %}
    {% else %}
      <div class="application-section">
        <p><a href="{% url 'teams:team_member_add' team.teamname %}" class="btn btn--blue btn--radius">メンバー追加申請をする</a></p>
      </div>
    {% endif %}
  </div>

{% endblock %}

{% block script %}

{% endblock %}

web/teams/templates/teams/team_profile/team_extends_base.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}'{% static "teams/scss/team_profile/dist/team_extends_base.css" %}'{% endblock %}

{% block head %}{% endblock %}

{% block content %}

  <img src="{{ team.header.url }}" alt="ヘッダー画像" class='header-img'>
  <div class='container'>
    <div class="div-icon-img">
      <img src="{{ team.icon.url }}" alt="アイコン画像" class='icon-img'>
    </div>

    <div class='name-edit-section'>
      <div class="name-section">
        <p class='profile-name'>{{ team.name }}</p>
      </div>
      <div class='edit-section'>
        {% if request.user.user_profile.team.teamname == team.teamname and request.user.user_profile.is_owner is True %}
        <p><a href="{% url 'teams:team_update' team.teamname %}" class="btn btn--blue btn--radius">編集する</a></p>
        {% endif %}
      </div>
    </div>

    <div class="username-team-section">
      <p class="sub-color">@{{ team.teamname }}</p>
    </div>

    <p class="introduction">{{ team.introduction }}</p>

    <div class='website-date-joined'>
      <p><a href="{{ team.website }}" target="_blank">{{ team.website | truncatechars:30 }}</a></p>
      <p class="sub-color">{{ team.created_at | date:"Y年n月" }}に作成されました</p>
    </div>

    {% if team.sponsor %}
    <div class="sponsor-section">
      <p class='sponsor-title'>スポンサー</p>
      <p>{{ team.sponsor | linebreaksbr }}</p>
    </div>
    {% endif %}
    </div>

    <div class="hr">
      <hr>
    </div>
    <div class='container'>
      <div class="lower-profile">
        <div class="game-section">
          <img src="{% static 'img/game-icon.svg' %}" alt="ゲームアイコン" class='svg'>
          <p>ゲーム</p>
          <a href="{% url 'teams:team_detail' team.teamname %}"></a>
        </div>
        <div class="member-section">
          <img src="{% static 'img/member-icon.svg' %}" alt="メンバーアイコン" class='svg'>
          <p>メンバー</p>
          <a href="{% url 'teams:team_detail_member' team.teamname %}"></a>
        </div>
        <div class="feature-section">
          <img src="{% static 'img/feature-icon.svg' %}" alt="特徴アイコン" class='svg'>
          <p>特徴</p>
          <a href="{% url 'teams:team_detail_feature' team.teamname %}"></a>
        </div>
        <div class="desired-condition-section">
          <img src="{% static 'img/desired-condition-icon.svg' %}" alt="希望条件アイコン" class='svg'>
          <p>希望条件</p>
          <a href="{% url 'teams:team_detail_desired_condition' team.teamname %}"></a>
        </div>
      </div>
    </div>
    <div class="hr">
      <hr>
    </div>

    {% block profile_content %}{% endblock %}


{% endblock %}

web/teams/templates/teams/team_profile/team_member_add.html
{% extends 'teams/team_profile/team_extends_base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'teams/scss/team_profile/dist/team_member_add.css' %}">
{% endblock %}

{% block profile_content %}

  <div class="container">
    <div class="form-section">
      <p class="title">メンバー追加を申請しますか？</p>
      <p>（メンバー追加を申請するとオーナーに通知が届きます。オーナーが許可するとチームのメンバー一覧に表示されるようになります。）</p>
      <form action="{% url 'teams:team_member_add' team.teamname %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="btn-section">
          <button type='submit' class="btn btn--blue btn--radius">送信する</button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

web/teams/templates/teams/team_profile/team_member_delete.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}'{% static "teams/scss/team_profile/dist/team_member_delete.css" %}'{% endblock %}

{% block content %}

  <div class="container">
    <h1 class="title">メンバーの削除</h1>
    <p>メンバー『<a href="{% url 'teams:account_detail' user.username %}">@{{ user.username }}</a>』を削除しますか？</p>
    <p><sup>※</sup>削除した後にメンバー追加をする場合は、再度申請を行ってもらう必要があります。</p>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="all-btn">
        <div class="btn-section">
          <a href="#" onclick="javascript:window.history.back(-1);return false;">
            <button type="submit" value="cancel" class="btn btn--blue btn--radius">キャンセル</button>
          </a>
        </div>
        <div class="btn-deny-section">
          <button name="approval" value="delete" class="btn btn--danger btn--radius">削除する</button>
        </div>
      </div>
    </form>
  </div>

{% endblock %}

web/teams/templates/teams/team_profile/team_member_list.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}'{% static "teams/scss/team_profile/dist/team_member_list.css" %}'{% endblock %}

{% block content %}
  <div class="container">
    <h1>チームメンバーリスト</h1>
    <p>下記から、削除したいメンバーを選択してください。</p>
    {% for profile in profiles %}
      {% if profile.is_owner is False %}
        <div class="user-section">
          <div>
            <a href="{% url 'teams:team_member_delete' profile.user.user_profile.team profile.user.username  %}">
              <img src="{{ profile.icon.url }}" alt="アイコン">
            </a>
          </div>
          <div>
            <p class="name"><a href="{% url 'teams:team_member_delete' profile.user.user_profile.team profile.user.username  %}" class="name">{{ profile.name }}</a></p>
          </div>
          <div>
            <p class="sub-color"><a href="{% url 'teams:team_member_delete' profile.user.user_profile.team profile.user.username  %}" class="sub-color">@{{ profile.user.username }}</a></p>
          </div>
        </div>
      {% elif profile.is_owner is True %}
        <div class="user-section">
          <div>
            <img src="{{ profile.icon.url }}" alt="アイコン">
          </div>
          <div class="name-margin">
            <p class="name">{{ profile.name }}</p>
          </div>
          <div class="name-margin">
            <p class="sub-color">@{{ profile.user.username }}</p>
          </div>
          <div class="sub-color name-margin">
            <p><sup>※</sup>オーナーは削除できません</p>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
  <div class="push"></div>
{% endblock %}