web/config/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static



admin.site.site_title = 'アプリ'
admin.site.site_header = 'アプリ管理画面'
admin.site.index_title = 'システム管理'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('', include('teams.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/teams/urls.py
from django.urls import path
from . import views



app_name = 'teams'

urlpatterns = [
    # サポートページ
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    # アカウントリスト
    path('accounts/list/', views.accounts_list, name='accounts_list'),
    # チーム
    path('team/create/', views.team_create, name='team_create'),
    path('team/list/', views.team_list, name='team_list'),
    path('team/<str:teamname>/update/', views.team_update, name='team_update'),
    path('team/<str:teamname>/delete/', views.team_delete, name='team_delete'),
    path('team/<str:teamname>/', views.team_detail, name='team_detail'),
    path('team/<str:teamname>/member/', views.team_detail_member, name='team_detail_member'),
    path('team/<str:teamname>/feature/', views.team_detail_feature, name='team_detail_feature'),
    path('team/<str:teamname>/desired_condition/', views.team_detail_desired_condition, name='team_detail_desired_condition'),
    # メンバー
    path('team/<str:teamname>/member/add/', views.team_member_add, name='team_member_add'),
    path('team/<str:teamname>/member/list/', views.team_member_list, name='team_member_list'),
    path('team/<str:teamname>/member/delete/<str:username>/', views.team_member_delete, name='team_member_delete'),
    # プロフィール
    path('<str:username>/', views.account_detail, name='account_detail'),
    path('<str:username>/feature/', views.account_detail_feature, name='account_detail_feature'),
    path('<str:username>/desired_condition/', views.account_detail_desired_condition, name='account_detail_desired_condition'),
    path('<str:username>/update/', views.account_profile_update, name='account_profile_update'),
    # 通知
    path('<str:username>/notification/', views.notification, name='notification'),
    path('<str:username>/notification/application/<uuid:id>/', views.application_detail, name='application_detail'),
    path('<str:username>/notification/invitation/<uuid:id>/', views.invitation_detail, name='invitation_detail'),
    path('<str:username>/notification/member_approval/<uuid:id>/', views.member_approval_detail, name='member_approval_detail'),
    path('<str:username>/notification/official/<uuid:id>/', views.official_detail, name='official_detail'),
    # リクエスト送信
    path('team/<str:teamname>/application/create/', views.application_create, name='application_create'),
    path('<str:username>/application/reply/create/<uuid:id>/', views.application_reply_create, name='application_reply_create'),
    # 招待送信
    path('<str:username>/invitation/create/', views.invitation_create, name='invitation_create'),
]

web/teams/models/faq.py
from django.db import models



class Question(models.Model):
    """
    よくある質問のモデル。
    アドミンページからの追加しかできない。
    """
    class Meta():
        db_table = 't_question'
        verbose_name = 'よくある質問'
        verbose_name_plural = 'よくある質問'

    id = models.AutoField(primary_key=True, editable=False)
    question = models.CharField(max_length=255, null=False, blank=False)
    awnser = models.CharField(max_length=1000, null=False, blank=False)

    def __str__(self):
        return self.question

web/teams/views/access.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import redirect
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured, PermissionDenied
from django.contrib.auth.mixins import AccessMixin



class OnlyYouMixin(UserPassesTestMixin):
    """
    本人のみアクセスできる Mixin。

    Attributes
    ----------
    raise_exception : bool
        raise exception を許すかの bool。
    """
    raise_exception = True

    def test_func(self):
        """
        request.user の username がアクセスしようとしている username と同じか確認する

        Returns
        -------
        bool
            True ならアクセス可能
            False ならアクセス不可
        """
        user = self.request.user
        return user.username == self.kwargs['username']



class OnlyOwnerMixin(UserPassesTestMixin):
    """
    チームのオーナーのみアクセスできる Mixin。

    Attributes
    ----------
    raise_exception : bool
        raise exception を許すかの bool。
    """
    raise_exception = True

    def test_func(self):
        """
        request.user の teamname がアクセスしようとしている teamname と同じか、 request.user はオーナーか確認する

        Returns
        -------
        bool
            True ならアクセス可能、False ならアクセス不可
        """
        user = self.request.user
        if user.is_authenticated:
            return user.user_profile.is_owner == True and user.user_profile.team.teamname == self.kwargs.get('teamname')
        else:
            return False



class CustomAccessMixin(AccessMixin):
    """
    AnonymousUser のみのアクセスに対応した Mixin を作成するため AccessMixin をカスタムしたクラス。
    親クラスと違うのは get_home_url の名前、 handle_no_permission の処理。
    """
    home_url = None

    def get_home_url(self):
        """
        AnonymousUser なら、 self.home_url もしくは 孫クラスの home_url にリダイレクトする関数。

        Raises
        ------
        ImproperlyConfigured
            ログインユーザーがアクセスした時にリダイレクトさせる URL がないため。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            孫クラスで定義した home_url もしくは、 settings.LOGIN_REDIRECT_URL に redirect。
        """
        home_url = self.home_url or settings.LOGIN_REDIRECT_URL
        if not home_url:
            raise ImproperlyConfigured(
                '{0} is missing the home_url attribute. Define {0}.home_url, settings.LOGIN_REDIRECT_URL, or override '
                '{0}.get_home_url().'.format(self.__class__.__name__)
            )
        return redirect(home_url)

    def handle_no_permission(self):
        """
        permission がないユーザーの画面処理。

        Parameters
        ----------
        self.raise_exception : bool
            孫クラスで定義。 raise_exception を許すかどうか。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            同クラスの get_home_url 関数の返り値の redirect。

        Raises
        ------
        PermissionDenied
            raise_exception True か request.user が未ログインのため。
            普通なら anonymous_user がこの処理を通ることはない（小クラスの dispatch 関数で anonymous_user がこの関数の処理を通らないようにしているため）。
        """
        if self.raise_exception or self.request.user.is_anonymous:
            raise PermissionDenied(self.get_permission_denied_message())
        return self.get_home_url()



class AnonymousRequiredMixin(CustomAccessMixin):
    """
    AnonymousUser のみアクセスできる Mixin。

    Examples
    --------
    AnonymousRequiredMixin を継承するのみで使用可能。
    home_url は任意。

    class SampleView(AnonymousRequiredMixin, TemplateView):
        home_url = 'views.home'
        # more ...
    """

    def dispatch(self, request, *args, **kwargs):
        """
        request.user はアクセス権限があるか判断する。
        ログインユーザーはアクセスできない。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            親クラスの get_home_url 関数の返り値の redirect。

        Any
            view の親クラスの dispatch 関数。
        """
        if request.user.is_authenticated:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

web/teams/views/application.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from .access import OnlyYouMixin
from teams.models import Team, Notification
from teams.forms import ApplicationCreateForm, ApplicationUpdateForm
from .team import TeamDetailBaseView



class ApplicationCreateView(LoginRequiredMixin, CreateView, TeamDetailBaseView):
    """
    チームリクエストを作成する。
    """
    template_name = 'teams/application_create.html'
    form_class = ApplicationCreateForm
    success_url = 'teams:team_detail'
    team_model = Team

    def form_valid_for_create_view(self, form):
        return super().form_valid(form)

    def form_valid(self, form):
        """
        application object に必要な情報を登録する。
        同じチームに所属している場合、無効になる。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            success_url に redirect。
        """
        self.object = form.save(commit=False)
        self.object.team = self.team_model.objects.get(teamname=self.kwargs.get('teamname'))
        self.user_team = self.request.user.user_profile.team
        if self.object.team == self.user_team or self.object.team.disclosed is False:
            return redirect(self.success_url, teamname=self.kwargs.get('teamname'))

        self.object.mode = 'application'
        self.object.from_user = self.request.user

        member = self.object.team.belonging_user_profiles.all()
        owner_profile = member.filter(is_owner=True)[0]
        self.object.to_user = owner_profile.user
        self.object.save()
        return self.form_valid_for_create_view(form)

    def get_success_url(self):
        """
        super().form_valid(form) が実行された後にリダイレクトする URL を取得する関数。

        See Also
        --------
        self.object.team.teamname : str
            form_valid 関数で取得したリクエストを送ろうとしている Team の teamname。
        """
        return reverse(self.success_url, kwargs={'teamname': self.object.team.teamname})

application_create = ApplicationCreateView.as_view()



class ApplicationReplyCreateView(LoginRequiredMixin, OnlyYouMixin, UpdateView):
    """
    リクエストの承認とその返答に必要なURLを入力するための view。
    """
    template_name = 'teams/notification/application_reply_create.html'
    form_class = ApplicationUpdateForm
    success_url = 'teams:notification'

    def form_valid_for_create_view(self, form):
        return super().form_valid(form)

    def form_valid(self, form):
        """
        チームリクエストオブジェクトを True にするのとURLをオブジェクトに登録する関数。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            get_success_url 関数で指定した url に redirect。
        """
        self.object = Notification.objects.get(id=self.kwargs.get('id'))
        if self.object.from_user == self.request.user or self.object.is_proceeded is False:
            return redirect('teams:home')
        self.object.is_proceeded = True
        self.object.invitation_url = form.cleaned_data['invitation_url']
        self.object.save()
        return self.form_valid_for_create_view(form)

    def get_context_data(self, **kwargs):
        """
        チームリクエストオブジェクトの編集に必要なオブジェクトを取得する関数。

        Returns
        -------
        dict
            チームリクエストオブジェクト入り ctx。
        """
        ctx = super().get_context_data(**kwargs)
        ctx['object'] = Notification.objects.get(id=self.kwargs.get('id'))
        return ctx

    def get_object(self):
        """
        URL に必要なパラメータを取得する関数。
        """
        return get_object_or_404(get_user_model(), username=self.kwargs.get('username'))

    def get_success_url(self):
        """
        super().form_valid(form) が実行された後にリダイレクトする URL を取得する関数。

        See Also
        --------
        self.request.user.username : str
            request.user の username。
        """
        return reverse(self.success_url, kwargs={'username': self.request.user.username})

application_reply_create = ApplicationReplyCreateView.as_view()

web/teams/views/invitation.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from teams.models import UserProfile
from teams.forms import InvitationCreateForm
from .profile import UserProfileBaseView



class InvitationCreateView(LoginRequiredMixin, CreateView, UserProfileBaseView):
    """
    ユーザー招待を作成する。
    """
    template_name = 'teams/invitation_create.html'
    form_class = InvitationCreateForm
    success_url = 'teams:account_detail'

    def form_valid(self, form):
        """
        invitation object に必要な情報を登録する。
        オーナーでない、もしくは本人に送信しようとしている場合、無効になる。

        Returns
        -------
        Union[HttpResponsePermanentRedirect, HttpResponseRedirect]
            success_url に redirect。
        """
        self.object = form.save(commit=False)
        if self.request.user.user_profile.is_owner == False:
            return redirect(self.success_url, username=self.kwargs.get('username'))
        self.object.mode = 'invitation'
        self.object.from_user = self.request.user
        self.object.invitation_user = get_user_model().objects.get(username=self.kwargs.get('username'))
        self.object.to_user = self.object.invitation_user
        if self.request.user == self.object.to_user or self.object.to_user.disclosed is False:
            return redirect(self.success_url, username=self.kwargs.get('username'))
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        """
        super().form_valid(form) が実行された後にリダイレクトする URL を取得する関数。

        See Also
        --------
        self.object.invitation_user : str
            招待を送ったユーザーの username
        """
        return reverse(self.success_url, kwargs={'username': self.object.invitation_user.username})

invitation_create = InvitationCreateView.as_view()

web/teams/views/profile.py
from django.shortcuts import get_object_or_404, resolve_url, redirect
from django.views.generic import DetailView, UpdateView, ListView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.db.models import Q
from functools import reduce
from operator import and_
from .access import OnlyYouMixin
from teams.models import Notification, UserProfile
from teams.forms import UserProfileUpdateForm



class UserProfileBaseView(DetailView):
    """
    ユーザープロフィールのデータを取得する
    """
    template_name = 'teams/accounts/profile_extends_base.html'
    model = UserProfile
    context_object_name = 'user_profile'

    def get_context_data(self, **kwargs):
        """
        ユーザープロフィール情報を取得する関数。

        Returns
        -------
        dict
            ユーザープロフィールオブジェクト入り ctx。
        """
        context = super().get_context_data(**kwargs)
        user = get_user_model().objects.get(username=self.kwargs.get('username'))
        context['user_profile'] = user.user_profile
        return context

    def get_object(self):
        return get_object_or_404(get_user_model(), username=self.kwargs.get('username'))


class UserProfileDetailGameView(UserProfileBaseView):
    """
    プロフィール下段のゲームを表示する
    """
    template_name = 'teams/accounts/account_detail_game.html'
    model = UserProfile

account_detail = UserProfileDetailGameView.as_view()



class UserProfileDetailFeatureView(UserProfileBaseView):
    """
    プロフィール下段の特徴を表示する
    """
    template_name = 'teams/accounts/account_detail_feature.html'
    model = UserProfile

account_detail_feature = UserProfileDetailFeatureView.as_view()



class UserProfileDetailDesiredConditionView(UserProfileBaseView):
    """
    プロフィール下段の希望条件を表示する
    """
    template_name = 'teams/accounts/account_detail_desired_condition.html'
    model = UserProfile

account_detail_desired_condition = UserProfileDetailDesiredConditionView.as_view()



class UserProfileUpdateView(LoginRequiredMixin, OnlyYouMixin, UpdateView):
    """
    プロフィールを更新する
    """
    template_name = 'teams/accounts/profile_update.html'
    model = UserProfile
    form_class = UserProfileUpdateForm
    success_url = 'teams:account_detail'

    def get_object(self):
        """
        URL に必要なパラメータを取得する関数。
        """
        return get_object_or_404(UserProfile, user=self.request.user)

    def get_success_url(self):
        """
        更新処理が完了した後に遷移する URL を取得する関数。
        """
        return resolve_url(self.success_url, username=self.kwargs.get('username'))

account_profile_update = UserProfileUpdateView.as_view()



class UserListView(ListView):
    """
    ユーザーの一覧表示・検索を行う。
    仕組みは TeamListView と同じ。
    """
    template_name = 'teams/accounts/accounts_list.html'
    model = UserProfile
    paginate_by = 100

    def get_queryset(self):
        """
        検索フォームに keyword が入力されたら、ユーザープロフィールモデルから検索をする処理。

        Returns
        -------
        Queryset
            検索ワードによって作られたクエリ。

        See Also
        --------
        keyword : html 検索バーから受け取った文字列
        """
        queryset = UserProfile.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')
        if keyword:
            exclusion = set([' ', '　'])
            q_list = ''
            for i in keyword:
                if i in exclusion:
                    pass
                else:
                    q_list += i
            query = reduce(and_, [Q(name__icontains=q) |
                                    Q(introduction__icontains=q) |
                                    Q(desired_condition__icontains=q)
                                    for q in q_list])
            queryset = queryset.filter(query)
        return queryset

accounts_list = UserListView.as_view()

web/teams/templates/teams/notification/application_detail.html
{% extends 'teams/notification/base_application_detail.html' %}
{% load static %}

{% block form_content %}

  {% if request.user == object.to_user %}
    {% if object.is_proceeded is None %}
    <form action="" method='POST'>
      {% csrf_token %}
      <p>このリクエストを許可しますか？<br>（「許可する」を押した場合、招待URL入力画面に移動します。）</p>
        <div class="all-btn">
          <div class="btn-deny-section">
            <button type="submit" name="approval" value="deny" class="btn btn--danger btn--radius">拒否する</button>
          </div>
          <div class="btn-section">
            <a href="{% url 'teams:application_reply_create' object.from_user.username object.id %}">
              <button name="approval" value="approve" class="btn btn--blue btn--radius">許可する</button>
            </a>
          </div>
        </div>
      </form>
    {% elif object.is_proceeded is True %}
      <p>すでに招待URLを送信しています。下記が送信したURLです。</p>
      <p><a href="{{ object.invitation_url }}">{{ object.invitation_url }}</a></p>
    {% elif object.is_proceeded is False %}
      <p>すでに、リクエストの認可を行っています。</p>
    {% endif %}



  {% elif request.user == object.from_user %}
    {% if object.is_proceeded is True %}
      <p>送信したリクエストが承認されました！下記が受信したURLです。このURLから会話を始めましょう！</p>
      <p><a href="{{ object.invitation_url }}">{{ object.invitation_url }}</a></p>
    {% elif object.is_proceeded is False %}
      <p>送信したリクエストは拒否されました。他に良いチームがないか探してみましょう！</p>
      <p><a href="{% url 'teams:team_list' %}">チームを探す</a></p>
    {% endif %}
  {% endif %}

{% endblock %}

web/teams/templates/teams/notification/application_reply_create.html
{% extends 'teams/notification/base_application_detail.html' %}
{% load static %}

{% block form_content %}

  <form action='{% url "teams:application_reply_create" object.to_user.username object.id %}' method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <div class="btn-section">
      <a href="{% url 'teams:application_reply_create' object.from_user.username object.id %}">
        <button type="submit" name="submit" class="btn btn--blue btn--radius">送信する</button>
      </a>
    </div>
  </form>

{% endblock %}

web/teams/templates/teams/notification/base_application_detail.html
{% extends 'teams/notification/notification_base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'teams/scss/notification/dist/base_application_detail.css' %}">
{% endblock %}

{% block notification_content %}

  {% if request.user == object.from_user %}
    <div class="from-user-section">
      <div>
        <a href="{% url 'teams:account_detail' object.to_user.username %}">
          <img src="{{ object.to_user.user_profile.icon.url }}" alt="アイコン">
        </a>
      </div>
      <div>
        <p class="from-user-name"><a href="{% url 'teams:account_detail' object.to_user.username %}" class="from-user-name">{{ object.to_user.user_profile.name }}</a></p>
      </div>
      <div>
        <p><a href="{% url 'teams:account_detail' object.to_user.username %}" class="sub-color">@{{ object.to_user.username }}</a></p>
      </div>
    </div>
    <p class="main-sentence">送信したメッセージ：{{ object.message }}</p>
    <p class="date">作成日時：{{ object.created_at }}</p>
  {% elif request.user == object.to_user %}
    <div class="from-user-section">
      <div>
        <a href="{% url 'teams:account_detail' object.from_user.username %}">
          <img src="{{ object.from_user.user_profile.icon.url }}" alt="アイコン">
        </a>
      </div>
      <div>
        <p class="from-user-name"><a href="{% url 'teams:account_detail' object.from_user.username %}" class="from-user-name">{{ object.from_user.user_profile.name }}</a></p>
      </div>
      <div>
        <p><a href="{% url 'teams:account_detail' object.from_user.username %}" class="sub-color">@{{ object.from_user.username }}</a></p>
      </div>
    </div>
    <p class="main-sentence">{{ object.message }}</p>
    <p class="date">受け取り日時：{{ object.created_at }}</p>
  {% endif %}

    {% block form_content %}{% endblock %}

{% endblock %}

web/teams/templates/teams/notification/notification.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}'{% static "teams/scss/notification/dist/notification.css" %}'{% endblock %}



{% block content %}

  <div class="container">

    <h3 class="title">通知</h3>
    <hr class="title-hr">
    {% if notifications %}
      {% for notification in notifications %}
        {% if request.user == notification.from_user %}
          {% if notification.sender_has_read is True %}
            <div class="notification-section">
          {% elif notification.sender_has_read is False %}
            <div class="notification-section unread">
          {% endif %}
        {% elif request.user == notification.to_user %}
          {% if notification.reciever_has_read is True %}
            <div class="notification-section">
          {% elif notification.reciever_has_read is False %}
            <div class="notification-section unread">
          {% endif %}
        {% endif %}

        {% if request.user == notification.to_user %}
          <div class="from-user-section">
            <div>
              <a href="{% url 'teams:account_detail' notification.from_user.username %}" class="inlink">
                <img src="{{ notification.from_user.user_profile.icon.url }}" alt="アイコン">
              </a>
            </div>
            <div>
              <p class="name"><a href="{% url 'teams:account_detail' notification.from_user.username %}" class="name inlink">{{ notification.from_user.user_profile.name }}</a></p>
            </div>
            <div>
              <p><a href="{% url 'teams:account_detail' notification.from_user.username %}" class="sub-color inlink">@{{ notification.from_user.username }}</a></p>
            </div>
          </div>
          {% if notification.is_proceeded is True or notification.is_proceeded is False %}
            {% if notification.mode == 'application' %}
              <div class="sentence">
                  <p>チームにリクエストが届きました。<sup>※</sup>返信済み</p>
                <p>{{ notification.message | truncatechars:30 }}</p>
              </div>
              <a href="{% url 'teams:application_detail' user.username notification.id %}"></a>
            {% elif notification.mode == 'invitation' %}
              <div class="sentence">
                  <p>あなたに招待が届きました。<sup>※</sup>返信済み</p>
                <p>{{ notification.message | truncatechars:30 }}</p>
              </div>
              <a href="{% url 'teams:invitation_detail' user.username notification.id %}"></a>
            {% elif notification.mode == 'member_approval' %}
              <div class="sentence">
                  <p>チームにメンバー追加の申請が届きました。<sup>※</sup>返信済み</p>
                <p>{{ notification.message | truncatechars:30 }}</p>
              </div>
              <a href="{% url 'teams:member_approval_detail' user.username notification.id %}"></a>
            {% elif notification.mode == 'official' %}
              <div class="sentence">
                <p>公式からのお知らせが届きました。</p>
                <p>{{ notification.message | truncatechars:30 }}</p>
              </div>
              <a href="{% url 'teams:official_detail' user.username notification.id %}"></a>
            {% endif %}
          {% else %}
            {% if notification.mode == 'application' %}
              <div class="sentence">
                  <p>チームにリクエストが届きました。</p>
                <p>{{ notification.message | truncatechars:30 }}</p>
              </div>
              <a href="{% url 'teams:application_detail' user.username notification.id %}"></a>
            {% elif notification.mode == 'invitation' %}
              <div class="sentence">
                  <p>あなたに招待が届きました。</p>
                <p>{{ notification.message | truncatechars:30 }}</p>
              </div>
              <a href="{% url 'teams:invitation_detail' user.username notification.id %}"></a>
            {% elif notification.mode == 'member_approval' %}
              <div class="sentence">
                  <p>チームにメンバー追加の申請が届きました。</p>
                <p>{{ notification.message | truncatechars:30 }}</p>
              </div>
              <a href="{% url 'teams:member_approval_detail' user.username notification.id %}"></a>
            {% elif notification.mode == 'official' %}
              <div class="sentence">
                <p>公式からのお知らせが届きました。</p>
                <p>{{ notification.message | truncatechars:30 }}</p>
              </div>
              <a href="{% url 'teams:official_detail' user.username notification.id %}"></a>
            {% endif %}
          {% endif %}

        {% elif request.user == notification.from_user %}
          <div class="from-user-section">
            <div>
              <a href="{% url 'teams:account_detail' notification.to_user.username %}" class="inlink">
                <img src="{{ notification.to_user.user_profile.icon.url }}" alt="アイコン">
              </a>
            </div>
            <div>
              <p class="name"><a href="{% url 'teams:account_detail' notification.to_user.username %}" class="name inlink">{{ notification.to_user.user_profile.name }}</a></p>
            </div>
            <div>
              <p><a href="{% url 'teams:account_detail' notification.to_user.username %}" class="sub-color inlink">@{{ notification.to_user.username }}</a></p>
            </div>
          </div>
          {% if notification.mode == 'application' %}
            <div class="sentence">
                <p>リクエストに対する返信が届きました。</p>
              <p>{{ notification.message | truncatechars:30 }}</p>
            </div>
            <a href="{% url 'teams:application_detail' user.username notification.id %}"></a>
          {% elif notification.mode == 'invitation' %}
            <div class="sentence">
                <p>招待に対する返信が届きました。</p>
              <p>{{ notification.message | truncatechars:30 }}</p>
            </div>
            <a href="{% url 'teams:invitation_detail' user.username notification.id %}"></a>
          {% elif notification.mode == 'member_approval' %}
            <div class="sentence">
                <p>メンバー追加の申請に対する返信が届きました。</p>
              <p>{{ notification.message | truncatechars:30 }}</p>
            </div>
            <a href="{% url 'teams:member_approval_detail' user.username notification.id %}"></a>
          {% elif notification.mode == 'official' %}
            <div class="sentence">
              <p>公式からのお知らせが届きました。</p>
              <p>{{ notification.message | truncatechars:30 }}</p>
            </div>
            <a href="{% url 'teams:official_detail' user.username notification.id %}"></a>
          {% endif %}
        {% endif %}

      </div>
      <hr class="notification-hr">
      {% endfor %}
    {% else %}
      <p class="none-notification">通知は届いていません。</p>
    {% endif %}
  </div>

  <div class="push"></div>

  {% endblock %}

web/teams/templates/teams/notification/notification_base.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}'{% static "teams/scss/notification/dist/notification_base.css" %}'{% endblock %}
{% block head %}{% endblock %}

{% block content %}

  <div class="container">
    <div class="back-section">
      <a href="#" onclick="javascript:window.history.back(-1);return false;">
        <img src="{% static 'img/arrow-icon.svg' %}" alt="矢印" class="arrow-icon">
      </a>
      <hr>
    </div>
    {% block notification_content %}{% endblock %}
  </div>

  <div class="push"></div>

{% endblock %}