web/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='account_login'),
    path('signup/', views.signup, name='account_signup'),
    path('logout/', views.logout, name='account_logout'),
    path('<str:username>/delete/', views.account_delete, name='account_delete'),
    path('settings/', views.account_settings, name='account_settings'),
]

web/config/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static



admin.site.site_title = 'アプリ'
admin.site.site_header = 'アプリ管理画面'
admin.site.index_title = 'システム管理'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('', include('teams.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/teams/urls.py
from django.urls import path
from . import views



app_name = 'teams'

urlpatterns = [
    # サポートページ
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    # アカウントリスト
    path('accounts/list/', views.accounts_list, name='accounts_list'),
    # チーム
    path('team/create/', views.team_create, name='team_create'),
    path('team/list/', views.team_list, name='team_list'),
    path('team/<str:teamname>/update/', views.team_update, name='team_update'),
    path('team/<str:teamname>/delete/', views.team_delete, name='team_delete'),
    path('team/<str:teamname>/', views.team_detail, name='team_detail'),
    path('team/<str:teamname>/member/', views.team_detail_member, name='team_detail_member'),
    path('team/<str:teamname>/feature/', views.team_detail_feature, name='team_detail_feature'),
    path('team/<str:teamname>/desired_condition/', views.team_detail_desired_condition, name='team_detail_desired_condition'),
    # メンバー
    path('team/<str:teamname>/member/add/', views.team_member_add, name='team_member_add'),
    path('team/<str:teamname>/member/list/', views.team_member_list, name='team_member_list'),
    path('team/<str:teamname>/member/delete/<str:username>/', views.team_member_delete, name='team_member_delete'),
    # プロフィール
    path('<str:username>/', views.account_detail, name='account_detail'),
    path('<str:username>/feature/', views.account_detail_feature, name='account_detail_feature'),
    path('<str:username>/desired_condition/', views.account_detail_desired_condition, name='account_detail_desired_condition'),
    path('<str:username>/update/', views.account_profile_update, name='account_profile_update'),
    # 通知
    path('<str:username>/notification/', views.notification, name='notification'),
    path('<str:username>/notification/application/<uuid:id>/', views.application_detail, name='application_detail'),
    path('<str:username>/notification/invitation/<uuid:id>/', views.invitation_detail, name='invitation_detail'),
    path('<str:username>/notification/member_approval/<uuid:id>/', views.member_approval_detail, name='member_approval_detail'),
    path('<str:username>/notification/official/<uuid:id>/', views.official_detail, name='official_detail'),
    # リクエスト送信
    path('team/<str:teamname>/application/create/', views.application_create, name='application_create'),
    path('<str:username>/application/reply/create/<uuid:id>/', views.application_reply_create, name='application_reply_create'),
    # 招待送信
    path('<str:username>/invitation/create/', views.invitation_create, name='invitation_create'),
]

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
  <title>CrowdGamers</title>
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel='stylesheet' type='text/css' href='{% static "scss/dist/base.css" %}'>
  <link rel='stylesheet' type='text/css' href={% block stylesheet %}{% endblock %}>
  {% block head %}{% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'teams:home' %}">CrowdGamers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class='nav-item'>
          <a class="nav-link" href="{% url 'teams:team_list' %}">
            <img src="{% static 'img/search-icon.svg' %}" alt="検索アイコン">
          </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class='nav-item'>
          <a class="nav-link" href="{% url 'teams:notification' request.user.username %}">
            <img src="{% static 'img/bell-icon.svg' %}" alt="通知アイコン" class='bell-icon'>
          </a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          {% if request.user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img src="{{ request.user.user_profile.icon.url }}" alt="アイコン" class='profile-icon'>
            </a>
          {% else %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="{% static 'img/default-icon.svg' %}" alt="デフォルトアイコン" class='profile-icon'>
            </a>
          {% endif %}

          {% if request.user.is_authenticated %}
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'teams:account_detail' request.user.username %}">プロフィール</a>
                <a class="dropdown-item" href="{% url 'accounts:account_settings' %}">設定</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:account_logout' %}">ログアウト</a>
            </div>
          {% else %}
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'accounts:account_login' %}">ログイン</a>
              <a class="dropdown-item" href="{% url 'accounts:account_signup' %}">登録</a>
            </div>
          {% endif %}
        </li>
        {% if request.user.is_authenticated %}
          <li class='nav-item'>
            <a class="nav-link" href="{% url 'teams:team_create' %}">
              <div class='img_wrap'>
                <img src="{% static 'img/create-button.svg' %}" alt="作成ボタン">
              </div>
            </a>
          </li>
        {% endif %}
      </ul>


    </div>
  </nav>

  {% block content %}{% endblock %}

  <footer>
    <h3>CrowdGamers</h3>
    <div class='content'>
      <div>
        <p><a href="{% url 'teams:home' %}">トップページ</a></p>
        <p><a href="{% url 'accounts:account_login' %}">ログイン・登録</a></p>
        <p><a href="{% url 'teams:team_list' %}">チームを探す</a></p>
        <p><a href="{% url 'teams:accounts_list' %}">プレイヤーを探す</a></p>
      </div>
      <div class='support'>
        <p><a href="{% url 'teams:faq' %}">よくある質問</a></p>
        <p><a href="{% url 'teams:terms_of_service' %}" target="_blank">利用規約</a></p>
        <p><a href="{% url 'teams:privacy_policy' %}" target="_blank">プライバシーポリシー</a></p>
        <p><a href="https://twitter.com/haruu_iq/" target="_blank">開発者情報</a></p>
      </div>
    </div>
    <p class='copyright'>Copyright &copy; 2021 CrowdGamers</p>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
          integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
          integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
          crossorigin="anonymous"></script>

  {% block script %}{% endblock %}
</body>
</html>